### PR TITLE
Custom decay example and case handling for closure object

### PR DESCRIPTION
**Pull request by terrytangyuan**
@jjallaire This doesn't work yet since closure object conversion is not implemented. Could you help work on the implementation so this example could run? 

Related issue: https://github.com/rstudio/tensorflow/issues/44

### CODE REVIEW

**Comment by terrytangyuan** [comment]
It is for this case but sometimes we need to pass a function that returns multiple items. For example:

```
def my_input_fn()

    # Preprocess your data here...

    # ...then return 1) a mapping of feature columns to Tensors with
    # the corresponding feature data, and 2) a Tensor containing labels
    return feature_cols, labels
```

This function could return multiple items and this `my_input_fn()` will be passed to `fit()`, like this:

```
classifier.fit(input_fn=my_input_fn, steps=2000)
```

**Comment by jjallaire** [comment]
That should still work fine. I'm assuming that `my_input_fun` will be written in R and will return an R list with 2 elements. The python function we synthesize to wrap it will call the R function then convert the 2-element R list to a Python tuple. Does that make sense?

**Comment by terrytangyuan** [comment]
Yes that makes sense. Right now there are only cases with 1-3 elements being returned.

**Comment by jjallaire** [comment]
I'm going to merge this PR then continue working on getting support for closures working on master.

**Comment by terrytangyuan** [comment]
Thanks!

**Comment by jjallaire** [comment]
I just checked in initial support for closures -- your example now seems to work!

Still need to do some polishing and write some tests but the basics should be there. Give it a try with some less trivial examples and let me know what you find.

**Comment by terrytangyuan** [comment]
Great! That was quick!

**Pull request merged**
