### PR TITLE
S3 method fix and added CITATION file

### PR DESCRIPTION
**Pull request by terrytangyuan**
Roxygen generates wrong items in NAMESPACE if S3 method is not specified explicitly:

Instead of this:
```
S3method(.DollarNames,tensorflow.builtin.object)
S3method(.DollarNames,tensorflow.python.platform.flags._FlagValues)
```

It generates this:
```
export(.DollarNames.tensorflow.builtin.object)
export(.DollarNames.tensorflow.python.platform.flags._FlagValues)
```

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@jjallaire @eddelbuettel Could you help take a look at the failure when you get a chance (after the break)? It's not introduced by this PR (you can probably reproduce it by rebuilding master branch).

**Comment by eddelbuettel** [comment]
Hm.  Last good run was 15 days ago?  Can you (just for kicks) branch from there and see if it also fails?

**Comment by terrytangyuan** [comment]
I guess it's just flaky for some reason. These are some builds on some of the commits in this PR. 
https://travis-ci.org/terrytangyuan/tensorflow-1/builds/178908103
https://travis-ci.org/terrytangyuan/tensorflow-1/builds/178897202
Sometimes fail on mac and sometimes fail on linux.

**Comment by eddelbuettel** [comment]
I prefer minimal Travis setups and generally do not do OS X or Appveyor/Windows just to avoid this.

**Comment by jjallaire** [comment]
Could you actually re-run roxygen so the NAMESPACE is updated as you intended?

@hadley It is indeed the case that there are some circumstances where `@export` won't work and you need `@method` explicitly (see the change in this PR for one possible example).

**Comment by terrytangyuan** [comment]
The current namespace in master branch should be correct.

**Comment by jjallaire** [comment]
Then I'm not sure why we need that change. Perhaps a machine that has an
older version of roxygen?

On Sun, Nov 27, 2016 at 9:45 AM, Yuan (Terry) Tang <notifications@github.com

**Comment by terrytangyuan** [comment]
Yeah maybe. I'll double check when I get back. Thanks!

**Comment by terrytangyuan** [comment]
@jjallaire @hadley I am using latest version of roxygen2 (5.0.1). It seems necessary for the change in this PR. Since when I run roxygen on master branch, I obtained the following git diff:
```
--- a/NAMESPACE
+++ b/NAMESPACE
@@ -36,8 +36,6 @@ S3method("^",tensorflow.python.framework.ops.Tensor)
 S3method("^",tensorflow.python.framework.ops.Variable)
 S3method("|",tensorflow.python.framework.ops.Tensor)
 S3method("|",tensorflow.python.framework.ops.Variable)
-S3method(.DollarNames,tensorflow.builtin.object)
-S3method(.DollarNames,tensorflow.python.platform.flags._FlagValues)
 S3method(abs,tensorflow.python.framework.ops.Tensor)
 S3method(abs,tensorflow.python.framework.ops.Variable)
 S3method(acos,tensorflow.python.framework.ops.Tensor)
@@ -79,6 +77,8 @@ S3method(tan,tensorflow.python.framework.ops.Tensor)
 S3method(tan,tensorflow.python.framework.ops.Variable)
 S3method(with,tensorflow.builtin.object)
 export("%as%")
+export(.DollarNames.tensorflow.builtin.object)
+export(.DollarNames.tensorflow.python.platform.flags._FlagValues)
 export(dict)
 export(import)
 export(parse_flags)
```

Am I missing anything else?

**Comment by jjallaire** [comment]
So perhaps there is a regression on roxygen master that requires the explicit use of `@method`? (or perhaps they have changed the roxygen behavior to require this?)

**Comment by hadley** [comment]
@jjallaire I'm pretty sure this is a bug that @kevinushey fixed in the dev version of roxygen2.

**Comment by terrytangyuan** [comment]
@hadley Just tried dev version via `devtools::install_github("klutometis/roxygen")`
Seems like it's still not fixed as well as introducing additional indentation. See following diff:
```
--- a/DESCRIPTION
+++ b/DESCRIPTION
@@ -17,27 +17,30 @@ Authors@R: c(
          comment = "Examples and Tutorials")
   )
 Description: TensorFlow is an open source software library for
-  numerical computation using data flow graphs. Nodes in the
-  graph represent mathematical operations, while the graph edges
-  represent the multidimensional data arrays (tensors) communicated
-  between them. The flexible architecture allows you to deploy
-  computation to one or more CPUs or GPUs in a desktop, server, or
-  mobile device with a single API. TensorFlow was originally developed
-  by researchers and engineers working on the Google Brain Team within
-  Google's Machine Intelligence research organization for the purposes
-  of conducting machine learning and deep neural networks research,
-  but the system is general enough to be applicable in a wide variety
-  of other domains as well.
+    numerical computation using data flow graphs. Nodes in the
+    graph represent mathematical operations, while the graph edges
+    represent the multidimensional data arrays (tensors) communicated
+    between them. The flexible architecture allows you to deploy
+    computation to one or more CPUs or GPUs in a desktop, server, or
+    mobile device with a single API. TensorFlow was originally developed
+    by researchers and engineers working on the Google Brain Team within
+    Google's Machine Intelligence research organization for the purposes
+    of conducting machine learning and deep neural networks research,
+    but the system is general enough to be applicable in a wide variety
+    of other domains as well.
 License: Apache License 2.0
 URL: https://github.com/rstudio/tensorflow
 BugReports: https://github.com/rstudio/tensorflow/issues
 SystemRequirements: Python (>= 2.7.0) with header files and shared library;
-  TensorFlow (https://www.tensorflow.org/)
+    TensorFlow (https://www.tensorflow.org/)
 Encoding: UTF-8
 LazyData: true
-Depends: R (>= 3.0)
+Depends:
+    R (>= 3.0)
 Imports:
-    utils, Rcpp (>= 0.12.7)
+    utils,
+    Rcpp (>= 0.12.7)
 LinkingTo: Rcpp
-RoxygenNote: 5.0.1
-Suggests: testthat
+RoxygenNote: 5.0.1.9000
+Suggests:
+    testthat
diff --git a/NAMESPACE b/NAMESPACE
index 176e45d..a9cf04f 100644
--- a/NAMESPACE
+++ b/NAMESPACE
@@ -36,8 +36,6 @@ S3method("^",tensorflow.python.framework.ops.Tensor)
 S3method("^",tensorflow.python.framework.ops.Variable)
 S3method("|",tensorflow.python.framework.ops.Tensor)
 S3method("|",tensorflow.python.framework.ops.Variable)
-S3method(.DollarNames,tensorflow.builtin.object)
-S3method(.DollarNames,tensorflow.python.platform.flags._FlagValues)
 S3method(abs,tensorflow.python.framework.ops.Tensor)
 S3method(abs,tensorflow.python.framework.ops.Variable)
 S3method(acos,tensorflow.python.framework.ops.Tensor)
@@ -79,6 +77,8 @@ S3method(tan,tensorflow.python.framework.ops.Tensor)
 S3method(tan,tensorflow.python.framework.ops.Variable)
 S3method(with,tensorflow.builtin.object)
 export("%as%")
+export(.DollarNames.tensorflow.builtin.object)
+export(.DollarNames.tensorflow.python.platform.flags._FlagValues)
 export(dict)
 export(import)
 export(parse_flags)
```

**Comment by terrytangyuan** [comment]
@jjallaire Could you merge this PR and we'll discuss the roxygen issue in its own Github repo? Otherwise I can imagine that new contributors to this repo would encounter the same issue.

**Comment by kevinushey** [comment]
@hadley the roxygen2 bug I fixed specifically pertained to 'internal' generics, e.g. `rbind` or `cbind`. roxygen2 does already detect that `.DollarNames` is an S3 generic:

```
roxygen2::is_s3_generic(".DollarNames")
```

However, that generic would not be discovered if the `utils` package is not loaded when searching for a generic. Does `tensorflow` need to explicitly import the `utils` namespace?

**Comment by kevinushey** [comment]
Wait, the version of `tensorflow` on master already has this in the NAMESPACE:

```
S3method(.DollarNames,tensorflow.builtin.object)
S3method(.DollarNames,tensorflow.python.platform.flags._FlagValues)
```

So AFAICS nothing needs to happen on the `tensorflow` side?

**Comment by terrytangyuan** [comment]
@kevinushey Please see my previous message. I tried both CRAN and dev version. Seems like those `S3method`s are replaced by `export`s when regenerating NAMESPACE file.

**Comment by hadley** [comment]
To provide a method, I'm pretty sure you have to import the generic. If that wasn't happening already, I think there would be an R CMD check or namespace loading problem.

**Comment by jjallaire** [comment]
Let's continue the coversation here (even though it's a closed PR) to preserve context until we are able determine that there is indeed an issue in roxygen dev version. The tensorflow package does indeed already import the .DollarNames method from utils: https://github.com/rstudio/tensorflow/blob/master/NAMESPACE#L88

Interestingly, for me both roxygen from CRAN and roxygen from GitHub correctly handle `.DollarNames` with only `@export`. I've therefore reverted the change to `@method` (https://github.com/rstudio/tensorflow/commit/1c3b2b3d38ea355f8871f4ae3482b31463b891e0) based on this as well as my understanding that `@method` should never be necessary if you've imported the S3 method as described earlier on this thread.

@terrytangyuan If you continue to have a repro for requiring `@method` let's follow up on the roxygen2 repository.

**Comment by terrytangyuan** [comment]
@jjallaire Thanks. Interesting. At first I thought it was a problem of my RStudio which shows up two roxygen2 libraries (CRAN and dev) so I uninstalled both of them and then tried installing each of them separately - still reproducing the issue. I also tried re-roxygenize from command line without going through RStudio - same issue. 

Anyways, if it's just me, then don't worry about it for now. Let's keep watching to see if other people encounter similar issue.

**Comment by kevinushey** [comment]
@terrytangyuan It would be useful to know some more information about your system -- e.g. what's the output of `utils::sessionInfo()`, and what operating system are you running with?

I can echo the fact that all seems well on OS X with R 3.3.2 + latest versions of `roxygen2`.

**Comment by terrytangyuan** [comment]
Sure @kevinushey 
```
> utils::sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] roxygen2_5.0.1.9000 Rcpp_0.12.8        

loaded via a namespace (and not attached):
 [1] crayon_1.3.2    digest_0.6.10   withr_1.0.1     commonmark_0.9  R6_2.2.0       
 [6] git2r_0.15.0    magrittr_1.5    httr_1.2.1      stringi_1.1.2   curl_0.9.7     
[11] xml2_1.0.0      desc_1.0.1      devtools_1.12.0 tools_3.2.3     stringr_1.1.0  
[16] memoise_1.0.0   knitr_1.12.3
```

```
➜  tensorflow-1 git:(master) R --version
R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)
```

**Pull request merged**
