### PR TITLE
Added mnist example for custom cnn model

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Comment by jjallaire** [comment]
Here's what I get when I run this locally against TF v0.12.1:

```
> classifier$fit(mnist_data$train$images, mnist_data$train$labels, steps = 100L)
WARNING:tensorflow:From <unknown>: calling fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From <unknown>: calling fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
Error in py_call(attrib, args, keywords) : 
  AttributeError: 'module' object has no attribute 'layers'
In addition: Warning messages:
1: In source("~/packages/tensorflow/inst/examples/tflearn/mnist_custom_cnn_model.R",  :
  integer literal 0.4L contains decimal; using numeric value
2: In source("~/packages/tensorflow/inst/examples/tflearn/mnist_custom_cnn_model.R",  :
  integer literal 0.001L contains decimal; using numeric value
> 
```

**Comment by jjallaire** [comment]
It looks like `layers` is not yet available in TF v0.12.1 (I think you are building against HEAD so it works fine on your end).

It would also be nice to remove these warnings in both this example and in the other tflearn examples:

```
WARNING:tensorflow:From <unknown>: calling fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
```

**Comment by terrytangyuan** [comment]
Yeah those warnings need to be fixed on Python end. I was on my way submitting my fixes but then realized one TF member has already worked on it internally. Hopefully it will be up soon.

**Comment by terrytangyuan** [comment]
@jjallaire I kept getting the following in TF/TF HEAD. Is there special arguments handling for float64 vs. float32? 
```
Error in py_call(attrib, args, keywords) : 
  TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type float64 of argument 'input'.
Detailed traceback: 
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/layers/base.py (line303): apply
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/layers/base.py (line285): __call__
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/layers/convolutional.py (line156): call
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py (line639): convolution
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py (line308): with_space_to_batch
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorfl
```

I am also skeptical that the examples were ran on Travis. 

I ran tests locally and here is the output:
```
Failed --------------------------------------------------------------------------------------
1. Failure: introduction.R example runs successfully (@test-examples.R#32) ------------------
run_example(example) threw an error.
AttributeError: 'module' object has no attribute 'mul'


2. Failure: mnist/mnist_softmax.R example runs successfully (@test-examples.R#32) -----------
run_example(example) threw an error.
AttributeError: 'module' object has no attribute 'mul'


3. Failure: mnist/fully_connected_feed.R example runs successfully (@test-examples.R#32) ----
run_example(example) threw an error.
ValueError: Only call `sparse_softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)
Detailed traceback: 
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py (line1533): _ensure_xent_args



4. Failure: tflearn/mnist_custom_cnn_model.R example runs successfully (@test-examples.R#32) 
run_example(example) threw an error.
TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type float64 of argument 'input'.
Detailed traceback: 
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/layers/base.py (line303): apply
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/layers/base.py (line285): __call__
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/layers/convolutional.py (line156): call
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py (line639): convolution
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py (line308): with_space_to_batch
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py (line631): op
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py (line140): _non_atrous_convolution
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py (line396): conv2d
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py (line772): apply_op



5. Failure: regression/tensorflow_linear_regression.R example runs successfully (@test-examples.R#32) 
run_example(example) threw an error.
AttributeError: 'module' object has no attribute 'sub'
```

**Comment by jjallaire** [comment]
Unless the 'mul' function was removed there is likely some sort of
configuration problem going on here.

What's the easist way for me to install TF HEAD so I can attempt to
reproduce locally?

**Comment by terrytangyuan** [comment]
I usually build from source: clone repo, Bazel build the pip package .whl
and pip install the .whl. Or you can pip install the nightly builds (you
can find the .whl link in the README installation section). I am away from
my computer now. I can find the specific urls later for you if needed.

**Comment by terrytangyuan** [comment]
Follow instruction in [this section](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#prepare-environment-for-mac-os-x) to prepare environment, call `./configure` and then build using `bazel` and `pip` following [this section](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#create-the-pip-package-and-install).

**Comment by jjallaire** [comment]
Okay, I repro'd the problem (it looks like they did actually rename the
'mul' function to 'multiply'. I'll get this resolved soon.

On Sat, Jan 21, 2017 at 1:09 PM, Yuan (Terry) Tang <notifications@github.com
> wrote:

> I usually build from source: clone repo, Bazel build the pip package .whl
> and pip install the .whl. Or you can pip install the nightly builds (you
> can find the .whl link in the README installation section). I am away from
> my computer now. I can find the specific urls later for you if needed.
>
> On Sat, Jan 21, 2017 at 1:00 PM JJ Allaire <notifications@github.com>
> wrote:
>
> > Unless the 'mul' function was removed there is likely some sort of
> >
> >
> > configuration problem going on here.
> >
> >
> >
> >
> >
> > What's the easist way for me to install TF HEAD so I can attempt to
> >
> >
> > reproduce locally?
> >
> >
> >
> >
> >
> > On Sat, Jan 21, 2017 at 11:50 AM, Yuan (Terry) Tang <
> >
> >

**Pull request closed without merging**
