### PR TITLE
bugfix to make extract syntax work in functions

### LINKED ISSUE #111: Unexpected behavior when extracting from tensors with higher dimension
I'm creating a function subset_tensor define with:

```
subset_tensor <- function(x, a, b){
  x[,0:(a-2), 0:(b-2),]
}
```

Then I apply it to a placeholder tensor:

```
k <- tf$placeholder(tf$float32, shape = c(1L, 600L, 600L, 3L))
subset_tensor(k, 600, 600)
#> Error in eval(expr, envir, enclos) : object 'b' not found
```

Note that it works if call directly:

```
k[,0:(600-2), 0:(600-2),]
Tensor("StridedSlice_5:0", shape=(1, 599, 599, 3), dtype=float32)
```

When I define a function `subset_tensor2` for a 2 dimension tensor, It works fine.

```
subset_tensor2 <- function(x, a, b){
  x[0:(a-2), 0:(b-2)]
}
subset_tensor2(l, 600, 600)
#> Tensor("StridedSlice_6:0", shape=(599, 599), dtype=float32)
```

Am I doing something wrong?

### PR DESCRIPTION
**Pull request by goldingn**
Fixes #111

Let me know if you want me to increment the patch number.

### CODE REVIEW

**Comment by goldingn** [comment]
wait, where'd the travis script go?

**Comment by goldingn** [comment]
Nevermind, [I see](https://github.com/rstudio/tensorflow/commit/96baf14876dc285f6f4d1774f5ca102dd5f8b7ef). That's annoying.

**Comment by jjallaire** [comment]
Great, thanks!

**Comment by jjallaire** [comment]
I'll take care of the version number

**Pull request merged**
