### PR TITLE
Fixing contrib attribute not found error in tensorflow 2.0

### PR DESCRIPTION
**Pull request by alexanderbeatson**
As I mentioned the weird error message in [here](https://github.com/rstudio/tensorflow/issues/394), it throws error message from TensorFlow that it doesn't have the attribute name contrib. I added the stop function with a message that tells the user eager execution is already running. 

Please edit the error message at your convenience. 

Thank you.

### CODE REVIEW

**Comment by dfalbel** [comment]
IMHO we should just return `NULL` when eager execution is already enabled to follow the TensorFlow python API. 

I'm not sure in which version `tf$executing_eagerly()` was added to the main API we should also check to call the appropriate function.

**Comment by alexanderbeatson** [comment]
@dfalbel 
As I checked other functions, they return error message using R stop() function. But, if you think returning NULL is better, may I request another pull request with returning NULL?

**Comment by dfalbel** [comment]
@alexanderbeatson sure! IMHO users would not want to have an error if you are enabling eager execution an it's already running.

**Comment by alexanderbeatson** [comment]
@dfalbel I just got an idea. Returning NULL alone would not make sense to some people. (They might think function is broken and they don't know eager is already running). So, I will return NULL with warning message. Thanks. Will make a pull request soon.

**Pull request closed without merging**
