### PR TITLE
Enhancements to `tensorboard()` and updated DESCIPTION

### PR DESCRIPTION
**Pull request by terrytangyuan**
Added `reload_interval` and `purge_orphaned_data` that will be useful in many scenarios.

### CODE REVIEW

**Comment by jjallaire** [comment]
To build the docs in this project you should use:

```r
source("tools/docs/build.R")
```

As that does some additional stuff required by our docs.

**Comment by jjallaire** [comment]
I'm actually wrong. That's keras that needs that. Looks good as is!

**Comment by jjallaire** [comment]
Actually, this project doesn't use pkgdown for docs at all, rather we maintain a website here: https://github.com/rstudio/tensorflow.rstudio.com

So I'd just remove the `docs` directory from this PR.

**Comment by terrytangyuan** [comment]
Gottcha. Just removed that folder!

**Comment by terrytangyuan** [comment]
I don't have access to that repo. Do I have to update the docs there?

**Comment by jjallaire** [comment]
We should probably add a section to the article in the other repo (just gave you access).

**Pull request merged**
